import { ArrowDownRight, ArrowRight, Check, CircleDot, FileCheck2, ScanSearch, Shield } from "lucide-react";
import { Link } from "wouter";
import { SignalViewport } from "@/components/SignalScopeUI";

export default function Home() {
  return <div className="home-page">
    <section className="hero"><div className="shell hero__grid"><div className="hero__copy"><div className="eyebrow eyebrow--rule">IMAGE AUTHENTICITY ANALYSIS <span>01 / 04</span></div><h1>See the signals<br /><em>behind an image.</em></h1><p className="hero__dek">SignalScope analyzes visual patterns associated with synthetic media and provides a confidence-based assessment with visual evidence.</p><div className="hero__actions"><Link href="/analyze" className="button button--primary">Analyze an image <ArrowRight size={17} /></Link><Link href="/how-it-works" className="button button--quiet">How it works <ArrowDownRight size={17} /></Link></div><div className="hero__trust"><span><Check size={14} /> Confidence-based</span><span><Check size={14} /> Visual evidence</span><span><Check size={14} /> Responsible by design</span></div></div><SignalViewport /></div></section>
    <section className="capability-strip"><div className="shell capability-strip__inner"><span className="capability-label">SYSTEM CAPABILITIES</span><div className="capability-list"><span>Transfer learning</span><span>Grad-CAM explanations</span><span>Robustness testing</span><span>Real-time analysis</span></div></div></section>
    <section className="statement-section"><div className="shell statement-grid"><div className="section-index mono">02 <span>/</span> CONTEXT</div><div><p className="large-statement">Synthetic media is getting harder to recognize. <strong>Better tools start with better questions.</strong></p><p className="statement-copy">SignalScope is built to make an image model’s assessment more legible — pairing a clear likelihood with the visual areas that shaped it.</p></div></div></section>
    <section className="home-process"><div className="shell"><div className="section-heading"><div><span className="eyebrow">A CLEARER WAY TO INSPECT</span><h2>From upload to understanding.</h2></div><Link href="/about" className="inline-link">Our approach <ArrowRight size={16} /></Link></div><div className="process-grid"><ProcessItem number="01" icon={<FileCheck2 size={19} />} title="Upload" text="Provide one image in a familiar format. Keep the source in view from the first step." /><ProcessItem number="02" icon={<ScanSearch size={19} />} title="Analyze" text="A trained classifier evaluates visual patterns associated with synthetic generation." /><ProcessItem number="03" icon={<CircleDot size={19} />} title="Inspect" text="Review likelihood, confidence, and a Grad-CAM explanation of model attention." /></div></div></section>
    <section className="home-note"><div className="shell home-note__inner"><Shield size={21} /><p><strong>Not a provenance oracle.</strong> SignalScope offers an analytical aid, not definitive proof of where an image came from.</p><Link href="/about">Read the limitations <ArrowRight size={15} /></Link></div></section>
  </div>;
}

function ProcessItem({ number, icon, title, text }: { number: string; icon: React.ReactNode; title: string; text: string }) { return <article className="process-item"><div className="process-item__top"><span className="process-item__number mono">{number}</span><span className="process-item__icon">{icon}</span></div><h3>{title}</h3><p>{text}</p></article>; }
