import { ArrowDown, ArrowRight, BrainCircuit, Check, Eye, FileImage, ScanSearch, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { PageIntro } from "@/components/SignalScopeUI";

const steps = [["01", "IMAGE INPUT", "One image enters the analysis flow."], ["02", "PREPROCESSING", "The image is prepared for the classifier."], ["03", "VISION MODEL", "EfficientNet-B0 performs binary classification."], ["04", "PROBABILITY", "The model returns a confidence-based likelihood."], ["05", "GRAD-CAM", "An explanation aid shows areas of model attention."], ["06", "RESPONSIBLE RESULT", "A clear assessment with limitations in view."]];

export default function HowItWorks() {
  return <div className="simple-page technical-page"><div className="shell"><PageIntro eyebrow="THE SIGNALSCOPE PIPELINE" title={<>From pixels to a<br /><em>responsible assessment.</em></>}><span>SignalScope combines a transfer-learning classifier with a visual explanation layer so the result is easier to inspect and harder to overread.</span></PageIntro><div className="pipeline">{steps.map(([number, title, text], index) => <div className="pipeline-step" key={number}><span className="pipeline-step__number mono">{number}</span><span className="pipeline-step__icon">{index === 0 ? <FileImage size={18} /> : index === 2 ? <BrainCircuit size={18} /> : index === 4 ? <Eye size={18} /> : <Check size={18} />}</span><div><strong>{title}</strong><p>{text}</p></div>{index < steps.length - 1 && <ArrowDown className="pipeline-step__connector" size={16} />}</div>)}</div><section className="architecture-section"><div className="architecture-copy"><span className="eyebrow">MODEL ARCHITECTURE</span><h2>EfficientNet-B0</h2><p>SignalScope uses a transfer-learning image classification model adapted for binary real-vs-AI image classification.</p><div className="architecture-tags"><span>224 × 224 preprocessing</span><span>Binary classification</span><span>Grad-CAM explanation</span></div></div><div className="architecture-diagram"><div>IMAGE</div><ArrowDown /><div>224 × 224</div><ArrowDown /><div className="is-accent">EfficientNet-B0</div><ArrowDown /><div>PROBABILITY</div><ArrowDown /><div>RESULT + EXPLANATION</div></div></section><section className="generalisation-callout"><div><span className="eyebrow">WHY UNSEEN GENERATORS MATTER</span><h2>Beyond the training distribution.</h2></div><p>A detector can perform well on familiar synthetic images while struggling with images produced by different generators. SignalScope therefore treats separate-generator evaluation as a key part of technical credibility.</p><Link href="/insights" className="inline-link">Explore insights <ArrowRight size={15} /></Link></section><section className="explanation-note"><ShieldCheck size={20} /><div><span className="eyebrow">RESPONSIBLE OUTPUT</span><p>Grad-CAM highlights regions that contributed more strongly to the model’s prediction. It is an explanation aid, not proof of manipulation or provenance.</p></div></section><div className="page-cta"><Link href="/analyze" className="button button--primary">Run the analysis flow <ArrowRight size={16} /></Link></div></div></div>;
}
