import { useEffect, useState } from "react";
import { Activity, ArrowRight, BarChart3, Check, Clock3, Database, Gauge, History as HistoryIcon, Trash2, TriangleAlert } from "lucide-react";
import { Link } from "wouter";
import { clearHistory, deleteHistory, getHistory, type HistoryEntry } from "@/api/history";
import { PageIntro } from "@/components/SignalScopeUI";

export function HistoryPage() {
  const [entries, setEntries] = useState<HistoryEntry[]>([]);
  useEffect(() => setEntries(getHistory()), []);
  return <div className="simple-page product-page"><div className="shell"><PageIntro eyebrow="LOCAL WORKSPACE" title={<>Analysis<br /><em>history.</em></>}><span>Your recent analyses stay on this device only. Nothing is uploaded here, and you can clear the record at any time.</span></PageIntro><div className="product-toolbar"><div><span className="eyebrow">RECENT ANALYSES</span><p>{entries.length ? `${entries.length} saved locally` : "No saved analyses"}</p></div>{entries.length > 0 && <button className="quiet-danger" onClick={() => { clearHistory(); setEntries([]); }}><Trash2 size={14} /> Clear history</button>}</div>{entries.length ? <div className="history-list">{entries.map((entry) => <HistoryRow key={entry.id} entry={entry} onDelete={() => { deleteHistory(entry.id); setEntries(getHistory()); }} />)}</div> : <div className="empty-product"><span className="empty-product__icon"><HistoryIcon size={22} /></span><h2>No analyses yet</h2><p>Your analyzed images will appear here.</p><Link href="/analyze" className="button button--primary">Analyze an image <ArrowRight size={16} /></Link></div>}</div></div>;
}

function HistoryRow({ entry, onDelete }: { entry: HistoryEntry; onDelete: () => void }) { const ai = entry.label.toLowerCase().includes("ai"); return <article className="history-row"><div className="history-thumb">{entry.thumbnail ? <img src={entry.thumbnail} alt="" /> : <Database size={20} />}</div><div className="history-info"><strong title={entry.filename}>{entry.filename || "Untitled image"}</strong><span className={`history-verdict ${ai ? "history-verdict--ai" : "history-verdict--real"}`}><i /> Likely {ai ? "AI Generated" : "Real"}</span><span className="mono">{Math.round(entry.confidence * 100)}% confidence · {new Date(entry.createdAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</span></div><div className="history-actions"><Link href="/analyze" className="inline-link">Re-analyze <ArrowRight size={14} /></Link><button className="icon-button" onClick={onDelete} aria-label={`Delete ${entry.filename || "analysis"}`}><Trash2 size={16} /></button></div></article>; }

const unavailable = "Awaiting final evaluation";
export function InsightsPage() {
  return <div className="simple-page product-page"><div className="shell"><PageIntro eyebrow="MODEL EVIDENCE" title={<>Does it<br /><em>generalize?</em></>}><span>Insights is reserved for measured project evidence. This interface intentionally does not invent benchmark values while evaluation is still being finalized.</span></PageIntro><EvidenceBanner /><section className="metric-section"><div className="product-section-head"><div><span className="eyebrow">OVERALL PERFORMANCE</span><h2>Evaluation metrics</h2></div><span className="mono">VALIDATION SET / PENDING</span></div><div className="metric-grid">{["ROC-AUC", "Macro-F1", "Accuracy", "False Positive Rate", "False Negative Rate"].map((label) => <Metric key={label} label={label} />)}</div></section><section className="evidence-layout"><div><div className="product-section-head"><div><span className="eyebrow">UNSEEN GENERATOR EVALUATION</span><h2>Beyond the training distribution</h2></div></div><p className="section-copy">A detector can perform well on familiar synthetic images while struggling with images produced by different generators. SignalScope evaluates generalisation on a separate generator distribution.</p><div className="unavailable-table">{["DALL·E", "Midjourney", "SDXL", "Stable Diffusion"].map((name) => <div key={name}><span>{name}</span><strong>{unavailable}</strong></div>)}</div></div><div className="confusion-card"><div className="product-section-head"><div><span className="eyebrow">CLASSIFICATION VIEW</span><h2>Confusion matrix</h2></div><BarChart3 size={17} /></div><div className="matrix"><span /> <b>Real</b><b>AI</b><b>Real</b><i>{unavailable}</i><i>{unavailable}</i><b>AI</b><i>{unavailable}</i><i>{unavailable}</i></div><p>A confusion matrix shows how often a model correctly and incorrectly classifies real and AI-generated images.</p></div></section><div className="page-cta"><Link href="/analyze" className="button button--primary">Test an image <ArrowRight size={16} /></Link></div></div></div>;
}

function EvidenceBanner() { return <div className="evidence-banner"><TriangleAlert size={18} /><div><strong>Evaluation data is configuration-ready.</strong><p>Connect verified measurements in the data configuration before presenting them in a demo. No placeholder statistics are shown as facts.</p></div></div>; }
function Metric({ label }: { label: string }) { return <div className="metric-card"><span>{label}</span><strong>{unavailable}</strong><small>Replace with measured result</small></div>; }

export function RobustnessPage() {
  const transformations = ["JPEG compression", "Resizing", "Blur", "Noise", "Brightness / contrast"];
  return <div className="simple-page product-page"><div className="shell"><PageIntro eyebrow="BONUS C / ROBUSTNESS" title={<>How stable is<br /><em>the detector?</em></>}><span>Real-world images are often compressed, resized, blurred, or lightly edited. Robustness testing measures how the detector behaves under these conditions.</span></PageIntro><EvidenceBanner /><section className="metric-section"><div className="product-section-head"><div><span className="eyebrow">DEGRADATION ANALYSIS</span><h2>Performance under change</h2></div><span className="mono">MEASURED RESULTS / PENDING</span></div><div className="robustness-grid">{transformations.map((name, index) => <article className="robust-card" key={name}><span className="robust-index mono">0{index + 1}</span><Activity size={18} /><h3>{name}</h3><div className="robust-flow"><span>Original</span><ArrowRight size={14} /><span>Transform</span><ArrowRight size={14} /><span>Result</span></div><strong>{unavailable}</strong></article>)}</div></section><div className="chart-placeholder"><div className="product-section-head"><div><span className="eyebrow">ROBUSTNESS PROFILE</span><h2>AUC by transformation</h2></div><Gauge size={17} /></div><div className="chart-empty"><BarChart3 size={22} /><span>Awaiting final evaluation data</span></div></div><div className="page-cta"><Link href="/analyze" className="button button--primary">Test an image <ArrowRight size={16} /></Link></div></div></div>;
}
